### ISSUE TITLE
LLVM 3.2 is out!

### ISSUE THREAD

**Issue by Nekroze** [jkm/deimos-llvm#1]
Can this be updated to llvm 3.2, it would be much appreciated! I would try myself however i have not had any luck making meaningful bindings.

**Comment by jkm** [comment]
Have you been using the bindings for version 3.1? Anything missing there? I'd rather finish these first.

**Comment by Nekroze** [comment]
i have yet to start my llvm project as i have been waiting on llvm 3.2, i figured why not wait since there was talk of the release being soon so no i havent tried 3.1 or the bindings so far nor do i intend to just to change my code later anyways. I guess i am not exactly ready to use the llvm bindings yet anyways so i can wait a bit before i need them, I just thought that it was a relatively simple thing to update.

Sorry if i am wrong and or naive just wanted to start with the latest and then stick to that. Cheers for the response mate.

**Comment by jkm** [comment]
I added 3.2 and also 3.3. Both can be accessed via tags and their respective branches.
I hope it won't take that long again next time when I need to add 3.4.
